"""add plan_configs and admin_audit_logs

Revision ID: 14431f9bac14
Revises: e92c3ad9d8e1
Create Date: 2026-07-24 14:11:02.720144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14431f9bac14'
down_revision: Union[str, Sequence[str], None] = 'e92c3ad9d8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('max_apps', sa.Integer(), nullable=True),
    sa.Column('max_modules', sa.Integer(), nullable=True),
    sa.Column('max_items', sa.Integer(), nullable=True),
    sa.Column('max_categories', sa.Integer(), nullable=True),
    sa.Column('max_push_sends_per_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_configs_id'), 'plan_configs', ['id'], unique=False)
    op.create_index(op.f('ix_plan_configs_plan_name'), 'plan_configs', ['plan_name'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_plan_configs_plan_name'), table_name='plan_configs')
    op.drop_index(op.f('ix_plan_configs_id'), table_name='plan_configs')
    op.drop_table('plan_configs')
    # ### end Alembic commands ###
