"""add item variations and reviews

Revision ID: 18d9bd4443c9
Revises: 2d503f7efed7
Create Date: 2026-07-25 14:41:49.071353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d9bd4443c9'
down_revision: Union[str, Sequence[str], None] = '2d503f7efed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('end_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['end_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['module_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'end_user_id', name='uq_item_reviews_item_end_user')
    )
    op.create_index(op.f('ix_item_reviews_id'), 'item_reviews', ['id'], unique=False)
    op.create_table('item_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['module_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_variations_id'), 'item_variations', ['id'], unique=False)
    op.add_column('order_items', sa.Column('item_variation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'item_variations', ['item_variation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item_variation_id')
    op.drop_index(op.f('ix_item_variations_id'), table_name='item_variations')
    op.drop_table('item_variations')
    op.drop_index(op.f('ix_item_reviews_id'), table_name='item_reviews')
    op.drop_table('item_reviews')
    # ### end Alembic commands ###
