"""add end_user_id to push_subscriptions

Revision ID: 2df7c4d4d1c0
Revises: c5d63a94cfe3
Create Date: 2026-07-25 17:46:47.654927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df7c4d4d1c0'
down_revision: Union[str, Sequence[str], None] = 'c5d63a94cfe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('end_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'push_subscriptions', 'app_users', ['end_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.drop_column('push_subscriptions', 'end_user_id')
    # ### end Alembic commands ###
