"""add order_status_events table

Revision ID: 6e03b721a4f5
Revises: 91f8f1f060a4
Create Date: 2026-07-26 19:21:01.850540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e03b721a4f5'
down_revision: Union[str, Sequence[str], None] = '91f8f1f060a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_events_id'), 'order_status_events', ['id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: pedidos já existentes ganham um evento inicial com o status
    # atual deles (usando updated_at, a melhor aproximação de quando aquele
    # status passou a valer) — sem isso a linha do tempo apareceria vazia
    # pra todo pedido feito antes desta migração.
    op.execute(
        """
        INSERT INTO order_status_events (order_id, status, created_at)
        SELECT id, status, updated_at FROM orders
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_events_id'), table_name='order_status_events')
    op.drop_table('order_status_events')
    # ### end Alembic commands ###
