"""add phone and address to app_users

Revision ID: 91f8f1f060a4
Revises: 2df7c4d4d1c0
Create Date: 2026-07-25 21:56:06.953149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f8f1f060a4'
down_revision: Union[str, Sequence[str], None] = '2df7c4d4d1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('app_users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'address')
    op.drop_column('app_users', 'phone')
    # ### end Alembic commands ###
