"""add coupons and order delivery fee/discount/fulfillment

Revision ID: c5d63a94cfe3
Revises: 18d9bd4443c9
Create Date: 2026-07-25 15:45:21.911810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d63a94cfe3'
down_revision: Union[str, Sequence[str], None] = '18d9bd4443c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order_value', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'code', name='uq_coupons_app_id_code')
    )
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.add_column('orders', sa.Column('delivery_fee', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('fulfillment_type', sa.String(), nullable=True))
    op.add_column('plan_configs', sa.Column('max_coupons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # seed_plan_configs() só insere linhas que faltam — planos 'pro'/'business' já
    # seedados em produção ficariam com max_coupons NULL/0 pra sempre sem isso.
    op.execute("UPDATE plan_configs SET max_coupons = 0 WHERE plan_name = 'free'")
    op.execute("UPDATE plan_configs SET max_coupons = 10 WHERE plan_name = 'pro'")
    op.execute("UPDATE plan_configs SET max_coupons = 999999 WHERE plan_name = 'business'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_configs', 'max_coupons')
    op.drop_column('orders', 'fulfillment_type')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'delivery_fee')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
