"""add group_name to item_variations

Revision ID: e76e0016d27f
Revises: 6e03b721a4f5
Create Date: 2026-07-26 21:48:14.774256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76e0016d27f'
down_revision: Union[str, Sequence[str], None] = '6e03b721a4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_variations', sa.Column('group_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_variations', 'group_name')
    # ### end Alembic commands ###
