"""add title/body to push_send_logs

Revision ID: e92c3ad9d8e1
Revises: 76ccc73ea47e
Create Date: 2026-07-24 13:46:58.667189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92c3ad9d8e1'
down_revision: Union[str, Sequence[str], None] = '76ccc73ea47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_send_logs', sa.Column('title', sa.String(), nullable=True))
    op.add_column('push_send_logs', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_send_logs', 'body')
    op.drop_column('push_send_logs', 'title')
    # ### end Alembic commands ###
