PLAN_LIMITS = {
    "free": {"apps": 1, "modules": 5, "items": 10, "categories": 5, "push_sends_per_month": 0, "coupons": 0},
    "pro": {"apps": 3, "modules": 10, "items": 100, "categories": 50, "push_sends_per_month": 5, "coupons": 10},
    "business": {"apps": 10, "modules": 100, "items": 10000, "categories": 150, "push_sends_per_month": 100, "coupons": 999999},
}

PLAN_PRICES = {
    "pro": 29.90,
    "business": 79.90,
}

SEED_MODULES = [
    {
        "name": "texto",
        "description": "Bloco de texto livre para informações do negócio",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Título", "Conteúdo em texto livre"],
    },
    {
        "name": "quem_somos",
        "description": "Apresentação institucional do negócio",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Título", "Texto de apresentação", "Imagem"],
    },
    {
        "name": "video",
        "description": "Vídeo embutido para captar atenção",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL do vídeo (YouTube/Vimeo)"],
    },
    {
        "name": "whatsapp",
        "description": "Botão de contato direto via WhatsApp",
        "category": "communication",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Número", "Mensagem padrão"],
    },
    {
        "name": "mapa",
        "description": "Localização do negócio com direcionamento",
        "category": "location",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Endereço", "Latitude/Longitude"],
    },
    {
        "name": "pagina_web",
        "description": "Integração de uma página web dentro do app",
        "category": "integration",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL da página"],
    },
    {
        "name": "radio_web",
        "description": "Transmissão contínua de rádio web",
        "category": "media",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL do stream", "Nome da rádio"],
    },
    {
        "name": "rss",
        "description": "Integração de feed RSS de blogs",
        "category": "integration",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL do feed"],
    },
    {
        "name": "wordpress",
        "description": "Exibição de postagens de um site WordPress",
        "category": "integration",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL do site"],
    },
    {
        "name": "google_agenda",
        "description": "Sincronização de eventos do Google Agenda",
        "category": "integration",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["URL de incorporação do calendário"],
    },
    {
        "name": "slider_imagens",
        "description": "Carrossel de imagens para destacar ofertas e novidades",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Lista de imagens"],
    },
    {
        "name": "chat_tawkto",
        "description": "Chat ao vivo integrado via Tawk.to",
        "category": "communication",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["ID do widget"],
    },
    {
        "name": "google_admob",
        "description": "Exibição de propagandas via Google AdMob",
        "category": "monetization",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["ID da unidade de anúncio"],
    },
    {
        "name": "cardapio",
        "description": "Cardápio digital com categorias e itens",
        "category": "food",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Categorias", "Itens com preço e foto"],
    },
    {
        "name": "catalogo",
        "description": "Catálogo de produtos para lojas",
        "category": "ecommerce",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Categorias", "Itens com preço e foto"],
    },
    {
        "name": "lista_itens",
        "description": "Lista de itens simples (textos e links organizados)",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Itens com nome e descrição"],
    },
    {
        "name": "galeria_imagens",
        "description": "Galeria de imagens do estabelecimento ou eventos",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Itens com imagem"],
    },
    {
        "name": "guia_empresas",
        "description": "Guia de empresas para divulgação local",
        "category": "content",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Itens com nome, telefone e endereço"],
    },
    {
        "name": "fale_conosco",
        "description": "Formulário de contato rápido",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Nome", "Email", "Mensagem"],
    },
    {
        "name": "formulario_delivery",
        "description": "Formulário de pedidos para delivery",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Nome", "Telefone", "Endereço", "Itens do pedido"],
    },
    {
        "name": "contato_personalizado",
        "description": "Formulário de contato com campos personalizados",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Campos definidos pelo dono do app"],
    },
    {
        "name": "form_fotos",
        "description": "Formulário de avaliação com envio de fotos",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "pro",
        "features": ["Avaliação por estrelas", "Comentário", "Foto"],
    },
    {
        "name": "cotacao",
        "description": "Formulário de solicitação de cotação",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Nome", "Contato", "Produto/serviço de interesse"],
    },
    {
        "name": "calculo_frete",
        "description": "Calculadora de frete por faixa de CEP",
        "category": "forms",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Regras de frete por prefixo de CEP"],
    },
    {
        "name": "login_cadastro",
        "description": "Login e cadastro de usuários do app",
        "category": "engagement",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Cadastro de clientes", "Login"],
    },
    {
        "name": "cartao_fidelidade",
        "description": "Cartão fidelidade com selos e prêmio",
        "category": "engagement",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Regra de pontuação", "Prêmio"],
    },
    {
        "name": "agenda_interna",
        "description": "Agenda de eventos e promoções",
        "category": "engagement",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Eventos com data e hora"],
    },
    {
        "name": "mercado_pago",
        "description": "Pagamento via Mercado Pago",
        "category": "payments",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Checkout Pro", "Cartão, Pix e boleto"],
    },
    {
        "name": "paypal",
        "description": "Pagamento via PayPal",
        "category": "payments",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Checkout internacional"],
    },
    {
        "name": "pagseguro",
        "description": "Pagamento via PagSeguro",
        "category": "payments",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Checkout nacional"],
    },
    {
        "name": "pagamento_entrega",
        "description": "Pagamento na entrega (dinheiro, cartão ou Pix)",
        "category": "payments",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Confirmação de pedido sem gateway"],
    },
    {
        "name": "push_notifications",
        "description": "Envio de notificações push para os usuários do app",
        "category": "engagement",
        "icon_url": None,
        "requires_plan": "pro",
        "features": ["Título e mensagem da notificação", "Envio para todos os inscritos"],
    },
    {
        "name": "mercado_livre",
        "description": "Produtos importados de uma conta do Mercado Livre",
        "category": "ecommerce",
        "icon_url": None,
        "requires_plan": "free",
        "features": ["Sincronização automática de produtos", "Preço e imagem do anúncio"],
    },
]

APP_TEMPLATES = {
    "restaurant": {
        "config": {"primary_color": "#E11D48", "secondary_color": "#F59E0B"},
        "modules": ["cardapio", "whatsapp", "fale_conosco", "mapa", "calculo_frete"],
    },
    "store": {
        "config": {"primary_color": "#4F46E5", "secondary_color": "#10B981"},
        "modules": ["catalogo", "whatsapp", "calculo_frete", "fale_conosco", "pagamento_entrega"],
    },
    "service": {
        "config": {"primary_color": "#0EA5E9", "secondary_color": "#6366F1"},
        "modules": ["fale_conosco", "whatsapp", "agenda_interna", "mapa", "cotacao"],
    },
    "delivery": {
        "config": {"primary_color": "#F97316", "secondary_color": "#22C55E"},
        "modules": ["cardapio", "formulario_delivery", "calculo_frete", "whatsapp", "pagamento_entrega"],
    },
    "other": {
        "config": {"primary_color": "#4F46E5", "secondary_color": "#10B981"},
        "modules": ["texto", "quem_somos", "whatsapp", "fale_conosco", "mapa"],
    },
    "beauty_salon": {
        "config": {"primary_color": "#DB2777", "secondary_color": "#A855F7"},
        "modules": ["agenda_interna", "whatsapp", "galeria_imagens", "fale_conosco", "mapa"],
    },
    "gym": {
        "config": {"primary_color": "#111827", "secondary_color": "#F97316"},
        "modules": ["agenda_interna", "cartao_fidelidade", "whatsapp", "mapa", "fale_conosco"],
    },
    "pet_shop": {
        "config": {"primary_color": "#0D9488", "secondary_color": "#FBBF24"},
        "modules": ["catalogo", "agenda_interna", "whatsapp", "calculo_frete", "fale_conosco"],
    },
    "real_estate": {
        "config": {"primary_color": "#1E3A8A", "secondary_color": "#CA8A04"},
        "modules": ["galeria_imagens", "contato_personalizado", "whatsapp", "mapa", "fale_conosco"],
    },
    "church_ngo": {
        "config": {"primary_color": "#1E40AF", "secondary_color": "#EAB308"},
        "modules": ["agenda_interna", "texto", "whatsapp", "mapa", "fale_conosco"],
    },
    "education": {
        "config": {"primary_color": "#4338CA", "secondary_color": "#14B8A6"},
        "modules": ["agenda_interna", "catalogo", "contato_personalizado", "fale_conosco", "whatsapp"],
    },
}

LIST_MODULES = {
    "cardapio": True,
    "catalogo": True,
    "lista_itens": False,
    "galeria_imagens": False,
    "guia_empresas": False,
    "agenda_interna": False,
}

ORDER_STATUS_LABELS = {
    "pending": "Pendente",
    "confirmed": "Confirmado",
    "preparing": "Preparando",
    "completed": "Concluído",
    "cancelled": "Cancelado",
}
